#include <iostream>
#include <stdlib.h>

#include "Turbine.h"

int main(){

	/* Calculate the power generated by the wind turbine*/
	std::string filename = "a170503.csv";
	double density = 0.5;
	double rotor_radius = 1;
	double power_coefficient = 1;
	char choice = '\0';

	Read read(filename);
	read.ReadStoreData();

	WindSpeed wind(density, read);

	Turbine turbine(rotor_radius, power_coefficient, wind);

	std::string first_date;
	std::string first_time;
	std::string last_date;
	std::string last_time;

	std::cout << "This program calculates the power generated from a turbine.\n"
		<< "The data is obtained from a set of csv files. The user should enter\n"
		<< "the date and time in the following format:\n"
		<< "Date: m/d/yy \n"
		<< "Time: hh:mm:ss \n"
		<< "There are four csv files to choose from \n"
		<< "5/3/17\n"
		<< "5/4/17\n"
		<< "5/5/17\n"
		<< "5/6/17\n"
		<< std::endl;


	do{
		std::cout << "Enter the start date: ";
		std::cin >> first_date;
		std::cout << std::endl;
		std::cout << "Enter the start time: ";
		std::cin >> first_time;
		std::cout << std::endl;

		std::cout << "Enter the end date: ";
		std::cin >> last_date;
		std::cout << std::endl;
		std::cout << "Enter the end time: ";
		std::cin >> last_time;
		std::cout << std::endl;


		turbine.wind->averageWind(first_date + ',' + first_time, last_date + ',' + last_time);

		std::cout << "Power Generated: " << turbine.TurbinePower() << std::endl;
		std::cout << "\n" << "Do you want to make another calculation (y/n): ";
		std::cin >> choice;
	} while (choice != 'n');



	std::cout << std::endl;
	//system("pause");
	return 0;
}

