#include <iostream>
#include <stdlib.h>

#include "Turbine.h"

int main(){
	/* Calculate the power generated by the wind turbine*/
	std::string filename = "a170503.csv";
	double density = 0.5;
	double rotor_radius = 1;
	double power_coefficient = 1;

	Read read(filename);
	read.ReadStoreData();
	std::cout << read.getData1().size() << std::endl;
	
	WindSpeed wind_speed(density,read);
	wind_speed.averageWind(5,20);

	std::cout << wind_speed.getDensity() << std::endl;
	std::cout << wind_speed.getWindSpeed() << std::endl;

	Turbine turbine(rotor_radius, power_coefficient, wind_speed);
	std::cout << turbine.TurbinePower() << std::endl;



	std::cout << std::endl;
	system("pause");
	return 0;
}